import { Household, Facility, FollowUp } from '@/types/enumerator';

export const dummyHouseholds: Household[] = [
  {
    id: '1',
    name: 'Rajesh Kumar',
    age: 45,
    gender: 'Male',
    phone: '9876543210',
    village: 'Rampur',
    householdSize: 5,
    source: 'AI',
    status: 'Draft',
    riskLevel: 'Yellow',
    hasSCCertificate: true,
    aadhaarLast4: '1234',
    rationCard: 'BPL123456',
    occupation: 'Farmer',
    incomeBracket: '< 50,000',
    housingType: 'Kaccha',
    hasToilet: false,
    hasElectricity: true,
    needsTraining: true,
    needsLivelihoodSupport: true,
    remarks: 'Family needs agricultural training',
  },
  {
    id: '2',
    name: 'Sunita Devi',
    age: 38,
    gender: 'Female',
    phone: '9876543211',
    village: 'Sitapur',
    householdSize: 4,
    source: 'Manual',
    status: 'Verified',
    riskLevel: 'Green',
    hasSCCertificate: true,
    aadhaarLast4: '5678',
    rationCard: 'APL987654',
    occupation: 'Tailor',
    incomeBracket: '50,000 - 1,00,000',
    housingType: 'Pucca',
    hasToilet: true,
    hasElectricity: true,
    needsTraining: false,
    needsLivelihoodSupport: false,
    verificationDecision: 'Verified Eligible',
  },
  {
    id: '3',
    name: 'Mukesh Yadav',
    age: 52,
    gender: 'Male',
    phone: '9876543212',
    village: 'Rampur',
    householdSize: 6,
    source: 'Paper',
    status: 'Pending Docs',
    riskLevel: 'Red',
    hasSCCertificate: false,
    aadhaarLast4: '9012',
    occupation: 'Daily Wage',
    incomeBracket: '< 50,000',
    housingType: 'Kaccha',
    hasToilet: false,
    hasElectricity: false,
    needsTraining: true,
    needsLivelihoodSupport: true,
    remarks: 'SC certificate pending submission',
  },
];

export const dummyFacilities: Facility[] = [
  {
    id: '1',
    type: 'Primary School',
    name: 'Government Primary School',
    village: 'Rampur',
    locationDescription: 'Near village center, main road',
    condition: 'Average',
    photos: ['school-front.jpg', 'school-playground.jpg'],
  },
  {
    id: '2',
    type: 'PHC',
    name: 'Primary Health Center',
    village: 'Sitapur',
    locationDescription: 'North side, near bus stand',
    condition: 'Good',
    photos: ['phc-entrance.jpg'],
  },
  {
    id: '3',
    type: 'Road',
    name: 'Main Village Road',
    village: 'Rampur',
    locationDescription: 'Connecting to highway',
    condition: 'Poor',
    photos: ['road-condition.jpg'],
  },
];

export const dummyFollowUps: FollowUp[] = [
  {
    id: '1',
    householdId: '3',
    name: 'Mukesh Yadav',
    village: 'Rampur',
    type: 'Docs Pending',
    resolved: false,
  },
  {
    id: '2',
    householdId: '1',
    name: 'Rajesh Kumar',
    village: 'Rampur',
    type: 'Training Follow-up',
    resolved: false,
  },
];
